const colors={p:'#087c60',e:'#b85b06',l:'#2463c4'};
let state={p:50,e:15,l:85,f:10,w:10};
const names={p:'支點位置',e:'力點位置',l:'重點位置',f:'施加的力',w:'重物的重量'};
const classes={p:'pivot',e:'effort',l:'load',f:'effort',w:'load'};
const byId=id=>document.getElementById(id);
byId('sliders').innerHTML=Object.keys(names).map(k=>`<div class="control ${classes[k]}"><label for="${k}">${names[k]}<output id="out-${k}"></output></label><input id="${k}" type="range" min="${k==='p'?10:k==='e'||k==='l'?5:0.1}" max="${k==='p'?90:k==='e'||k==='l'?95:100}" step="${k==='f'||k==='w'?0.1:1}" value="${state[k]}"></div>`).join('');
function physics(s=state){const a=Math.abs(s.e-s.p),b=Math.abs(s.l-s.p),dir=-Math.sign((s.e-s.p)*(s.l-s.p));return{a,b,dir,need:s.w*b/a,torque:s.w*(s.l-s.p)+s.f*dir*(s.e-s.p)}}
function configure(patch){const next={...state,...patch};for(const k of Object.keys(patch)){if(!Object.hasOwn(state,k)||!Number.isFinite(patch[k]))throw Error('請輸入有效數值');const min=k==='p'?10:k==='e'||k==='l'?5:.1,max=k==='p'?90:k==='e'||k==='l'?95:100;if(patch[k]<min||patch[k]>max)throw Error('數值超出範圍');}if(Math.abs(next.p-next.e)<3||Math.abs(next.p-next.l)<3||Math.abs(next.e-next.l)<3)throw Error('三個位置至少相隔 3 cm，請稍微移開。');state=next;render();return{...state,...physics()}}
function render(){const q=physics(),balanced=Math.abs(q.torque)<.08,angle=balanced?0:Math.max(-14,Math.min(14,q.torque/(state.w*q.b+state.f*q.a)*14)),r=angle*Math.PI/180,pX=80+state.p*8;
for(const k of Object.keys(names)){byId(k).value=state[k];byId('out-'+k).textContent=state[k].toFixed(k==='f'||k==='w'?1:0)+(k==='f'||k==='w'?' N':' cm');}
const pos=k=>({x:pX+(state[k]-state.p)*8*Math.cos(r),y:240+(state[k]-state.p)*8*Math.sin(r)});
const point=(k,label)=>{const c=pos(k);return `<g data-drag="${k}" class="draggable"><circle cx="${c.x}" cy="${c.y}" r="27" fill="${colors[k]}" stroke="white" stroke-width="4"/><text x="${c.x}" y="${c.y+6}" text-anchor="middle" fill="white" font-size="19" font-weight="750">${label}</text></g>`};
const arrow=(k,dir,label)=>{const c=pos(k),from=c.y-dir*102,to=c.y-dir*35;return `<path d="M${c.x} ${from}V${to}" stroke="${colors[k]}" stroke-width="5" marker-end="url(#arrow-${k})"/><text x="${c.x}" y="${dir===1?from-14:from+28}" text-anchor="middle" fill="${colors[k]}" font-size="21" font-weight="700">${label}</text>`};
byId('lever').innerHTML=`<defs>${['e','l'].map(k=>`<marker id="arrow-${k}" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="4" markerHeight="4" orient="auto-start-reverse"><path d="M0 0 10 5 0 10" fill="${colors[k]}"/></marker>`).join('')}</defs><path d="M50 335H910" stroke="#cfdae2" stroke-width="2"/><path d="M${pX} 251l-46 81h92z" fill="#c8e7dc" stroke="${colors.p}" stroke-width="3"/><g transform="rotate(${angle} ${pX} 240)"><rect x="80" y="231" width="800" height="18" rx="9" fill="#254459"/>${Array.from({length:21},(_,i)=>`<path d="M${80+i*40} 232v${i%2?5:9}" stroke="#8aa0b0" stroke-width="2"/>`).join('')}</g>${arrow('e',q.dir,`${state.f.toFixed(1)} N ${q.dir===1?'↓':'↑'}`)}${arrow('l',1,`${state.w.toFixed(1)} N ↓`)}${point('e','力')}${point('l','重')}${point('p','支')}<text x="${pX}" y="363" text-anchor="middle" fill="${colors.p}" font-size="20" font-weight="700">支點</text><path d="M${Math.min(pos('e').x,pX)} 405H${Math.max(pos('e').x,pX)}" stroke="${colors.e}" stroke-width="3"/><text x="${(pos('e').x+pX)/2}" y="435" text-anchor="middle" fill="${colors.e}" font-size="18">力臂 ${ (q.a*Math.cos(r)).toFixed(1)} cm</text><path d="M${Math.min(pos('l').x,pX)} 455H${Math.max(pos('l').x,pX)}" stroke="${colors.l}" stroke-width="3"/><text x="${(pos('l').x+pX)/2}" y="480" text-anchor="middle" fill="${colors.l}" font-size="18">重臂 ${(q.b*Math.cos(r)).toFixed(1)} cm</text>`;
byId('status').textContent=balanced?'槓桿平衡！兩邊的轉動作用相等。':q.torque*(state.l-state.p)>0?'重物向下：試試增加力度，或把力點移遠。':'重物向上：你施加的力足以提起重物。';
byId('effort-arm').textContent=(q.a*Math.cos(r)).toFixed(1)+' cm';byId('load-arm').textContent=(q.b*Math.cos(r)).toFixed(1)+' cm';byId('needed').textContent=q.need.toFixed(1)+' N';byId('advantage').textContent=q.a>q.b?'省力：所需的力小於重物的重量':q.a<q.b?'費力：所需的力大於重物的重量':'所需的力等於重物的重量';byId('calculation').textContent=`${state.f.toFixed(1)} × ${(q.a*Math.cos(r)).toFixed(1)} ${balanced?'＝':'≠'} ${state.w.toFixed(1)} × ${(q.b*Math.cos(r)).toFixed(1)}`;}
Object.keys(names).forEach(k=>byId(k).addEventListener('input',e=>{try{configure({[k]:Number(e.target.value)});byId('error').textContent=''}catch(err){byId('error').textContent=err.message;e.target.value=state[k]}}));
let dragging=null;byId('lever').addEventListener('pointerdown',e=>{const target=e.target.closest('[data-drag]');if(target){dragging=target.dataset.drag;byId('lever').setPointerCapture(e.pointerId);e.preventDefault()}});byId('lever').addEventListener('pointermove',e=>{if(!dragging)return;const svg=byId('lever'),pt=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse()),min=dragging==='p'?10:5,max=dragging==='p'?90:95,v=Math.max(min,Math.min(max,Math.round((pt.x-80)/8)));try{configure({[dragging]:v});byId('error').textContent=''}catch(err){byId('error').textContent=err.message}});['pointerup','pointercancel','lostpointercapture'].forEach(n=>byId('lever').addEventListener(n,()=>dragging=null));
byId('reset').onclick=()=>{state={p:50,e:15,l:85,f:10,w:10};byId('error').textContent='';render()};byId('balance').onclick=()=>{const n=physics().need;if(n>100){byId('error').textContent='所需的力超過 100 N；請把力點移遠或把重點移近支點。';return}state.f=n;byId('error').textContent='';render()};document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{state={p: b.dataset.preset==='first'?50:20,e:b.dataset.preset==='third'?50:85,l:b.dataset.preset==='first'?85:b.dataset.preset==='second'?50:85,f:10,w:10};if(b.dataset.preset==='first')state.e=15;byId('error').textContent='';render()});
window.leverLab={configure,read:()=>({...state,...physics()})};render();if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'configure_lever',description:'調整槓桿的位置及力，並回傳平衡所需的力。',inputSchema:{type:'object',properties:Object.fromEntries(Object.keys(names).map(k=>[k,{type:'number',description:names[k]}])),additionalProperties:false},annotations:{readOnlyHint:false},execute:configure})}catch{}}
