const $=id=>document.getElementById(id);const labels={p:'支點',e:'力點',l:'重點'},colors={p:'#087c60',e:'#b85b06',l:'#2463c4'},cls={p:'pivot',e:'effort',l:'load'};
const items=[
{name:'蹺蹺板',scenario:'左邊的人向下用力，提起右邊的人。把標籤放到對應的位置。',points:[[450,230,'p'],[170,230,'e'],[730,230,'l']],hint:'蹺蹺板繞着中間的座轉動；左邊施力，右邊是要提起的重量。',explain:'中間的座是支點；左邊向下用力的位置是力點；右邊重量作用的位置是重點。支點在中間。',svg:'<path d="M100 230H800" stroke="#476178" stroke-width="22" stroke-linecap="round"/><path d="m450 240-65 105h130z" fill="#c8d8e1" stroke="#476178" stroke-width="4"/><path d="M160 130v55m-17-17 17 17 17-17" stroke="#b85b06" stroke-width="7" fill="none"/><rect x="691" y="149" width="78" height="64" rx="9" fill="#dbe7f9" stroke="#2463c4" stroke-width="3"/><text x="160" y="102">人向下用力</text><text x="730" y="124">要提起的人</text>'},
{name:'剪刀',scenario:'手握下方的手柄，剪開刀刃間的紙張。這題辨認與下方手柄相連的那一片剪刀。',points:[[450,235,'p'],[190,325,'e'],[660,164,'l']],hint:'先找連接兩片剪刀的螺絲，再找手握的位置和剪紙的位置。',explain:'螺絲是支點；手握手柄的位置是力點；刀刃剪紙、克服紙張阻力的位置是重點。支點在中間。',svg:'<rect x="615" y="108" width="125" height="126" fill="#fff" stroke="#c5d3df" stroke-width="3"/><path d="M252 300 720 143 690 171 260 318z" fill="#9db3c5" stroke="#476178" stroke-width="3"/><path d="M252 167 720 325 690 300 260 150z" fill="#cad7e0" stroke="#476178" stroke-width="3"/><ellipse cx="190" cy="325" rx="72" ry="45" fill="none" stroke="#df8c2b" stroke-width="22" transform="rotate(-18 190 325)"/><ellipse cx="190" cy="143" rx="72" ry="45" fill="none" stroke="#df8c2b" stroke-width="22" transform="rotate(18 190 143)"/><circle cx="450" cy="235" r="14" fill="#fff" stroke="#476178" stroke-width="5"/><text x="182" y="405">手握這個手柄</text><text x="694" y="82">紙張</text>'},
{name:'手推車',scenario:'雙手向上提起車把，使車斗和貨物抬起。',points:[[215,295,'p'],[755,230,'e'],[465,245,'l']],hint:'抬起車把時，車身繞着輪軸轉動。貨物位於輪軸和車把之間。',explain:'輪軸是支點；手提起車把的位置是力點；貨物重量作用在車斗的位置是重點。重點在中間，因此可以省力。',svg:'<circle cx="215" cy="295" r="65" fill="#e4edf3" stroke="#476178" stroke-width="12"/><circle cx="215" cy="295" r="10" fill="#476178"/><path d="M215 295 350 230H775" fill="none" stroke="#476178" stroke-width="12" stroke-linecap="round"/><path d="M275 155h350l-60 92H340z" fill="#b6d6dc" stroke="#476178" stroke-width="4"/><rect x="400" y="95" width="95" height="70" rx="5" fill="#f2c075" stroke="#b98336" stroke-width="3"/><rect x="505" y="120" width="65" height="45" rx="4" fill="#f2c075" stroke="#b98336" stroke-width="3"/><path d="M755 197v-65m-17 17 17-17 17 17" stroke="#b85b06" stroke-width="7" fill="none"/><text x="483" y="73">貨物</text><text x="755" y="101">向上提起車把</text>'},
{name:'鑷子',scenario:'手指按壓鑷子的中段，以尖端夾起小物件。這題辨認下方的一片鑷子。',points:[[175,225,'p'],[450,273,'e'],[748,325,'l']],hint:'鑷子的兩片在左端連接。手在中段施力，尖端夾物件。',explain:'左端連接處是支點；手指按壓的中段是力點；尖端克服物件阻力的位置是重點。力點在中間，較費力，但尖端可移動較大的距離。',svg:'<path d="M175 225 760 123 760 141 175 236z" fill="#c2d0dc" stroke="#476178" stroke-width="3"/><path d="M175 225 760 316 760 334 175 238z" fill="#9db6c8" stroke="#476178" stroke-width="3"/><path d="M175 225v13" stroke="#476178" stroke-width="16"/><rect x="727" y="202" width="50" height="70" rx="7" fill="#edb666" stroke="#b98336" stroke-width="3"/><path d="M450 386v-67m-17 17 17-17 17 17" stroke="#b85b06" stroke-width="7" fill="none"/><text x="450" y="425">手指向內按壓</text><text x="779" y="190">小物件</text>'}
];
let index=0,assigned={},selected=null,completed=new Set(),ghost=null,activePointer=null;function render(){const item=items[index];$('objects').innerHTML=items.map((o,i)=>`<button class="${i===index?'active':''}" data-item="${i}" ${i===index?'aria-current="true"':''}>${o.name}<small>${completed.has(i)?'✓':''}</small></button>`).join('');$('objects').querySelectorAll('button').forEach(b=>b.onclick=()=>switchItem(Number(b.dataset.item)));$('object-title').textContent=item.name;$('progress').textContent=`第 ${index+1} / ${items.length} 件 · 已完成 ${completed.size} 件`;$('scenario').textContent=item.scenario;$('diagram').innerHTML=`<svg viewBox="0 0 900 460" role="img" aria-label="${item.name}的支點、力點與重點辨認示意圖"><g fill="#526471" font-size="18" text-anchor="middle">${item.svg}</g>${item.points.map(([x,y,key],i)=>{const a=assigned[i];return `<g class="target" data-slot="${i}" tabindex="0" role="button" aria-label="位置 ${i+1}，${a?labels[a]:'未放置'}"><circle cx="${x}" cy="${y}" r="35" ${a?`style="stroke:${colors[a]};fill:#fff;stroke-dasharray:none"`:''}/><text x="${x}" y="${y}" fill="${a?colors[a]:'#526471'}">${a?labels[a]:'?'}</text></g>`}).join('')}</svg>`;$('diagram').querySelectorAll('[data-slot]').forEach(t=>{t.onclick=()=>place(Number(t.dataset.slot));t.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();place(Number(t.dataset.slot))}}});$('tray').innerHTML=Object.keys(labels).map(k=>`<button data-label="${k}" class="${cls[k]} ${selected===k?'selected':''} ${Object.values(assigned).includes(k)?'placed':''}" aria-pressed="${selected===k}">${labels[k]}</button>`).join('');$('tray').querySelectorAll('button').forEach(b=>{b.onclick=()=>{selected=b.dataset.label;render()};b.onpointerdown=e=>{activePointer={id:e.pointerId,k:b.dataset.label,x:e.clientX,y:e.clientY,moved:false};b.setPointerCapture(e.pointerId)}})}
function message(text,type=''){const el=$('feedback');el.className='feedback '+type;el.textContent=text}
function place(slot,key=selected){if(!key){message('先點選一個標籤，再點選圖中的位置。');return}for(const s in assigned)if(assigned[s]===key)delete assigned[s];assigned[slot]=key;selected=null;render();message('已放置標籤。三個都放好後，按「檢查答案」。')}
function switchItem(i){index=i;assigned={};selected=null;render();message('先找出物品繞着哪個位置轉動。')}
document.addEventListener('pointermove',e=>{if(!activePointer||e.pointerId!==activePointer.id)return;if(Math.hypot(e.clientX-activePointer.x,e.clientY-activePointer.y)>6){activePointer.moved=true;if(!ghost){ghost=document.createElement('div');ghost.className='drag-ghost';ghost.textContent=labels[activePointer.k];document.body.append(ghost)}ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px'}});document.addEventListener('pointerup',e=>{if(!activePointer||e.pointerId!==activePointer.id)return;const drag=activePointer;if(drag.moved){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot]');if(target)place(Number(target.dataset.slot),drag.k);else{selected=drag.k;render();message('請把標籤放到圖中的圓圈，或點選圓圈。')}}ghost?.remove();ghost=null;activePointer=null});document.addEventListener('pointercancel',()=>{ghost?.remove();ghost=null;activePointer=null});
$('retry').onclick=()=>switchItem(index);$('hint').onclick=()=>message(items[index].hint);$('next').onclick=()=>switchItem((index+1)%items.length);$('check').onclick=()=>{if(Object.keys(assigned).length<3){message('還有位置未放好。請放置支點、力點和重點。','error');return}const count=items[index].points.filter((p,i)=>assigned[i]===p[2]).length;if(count===3){completed.add(index);render();message('全部正確！'+items[index].explain,'success')}else message(`你找對了 ${count} 個位置。再想想：哪裏轉動？哪裏施力？哪裏承受重物或阻力？`,'error')};
window.leverPractice={read:()=>({index,assigned:{...assigned},completed:[...completed]}),switchItem,place};render();
